//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Forum_cSharp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; 
    
    public partial class Comment
    {
        public Comment()
        {
            this.Comment1 = new HashSet<Comment>();
        }
    
        public int CommentId { get; set; }
        public int ThreadId { get; set; }
        public Nullable<int> ParentCommentId { get; set; }
        public string UserName { get; set; }
        public System.DateTime Date { get; set; }
        [Required]
        public string Content { get; set; }
    
        public virtual ICollection<Comment> Comment1 { get; set; }
        public virtual Comment Comment2 { get; set; }
        public virtual Thread Thread { get; set; }
    }
}
