//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Forum_cSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.TagThreads = new HashSet<TagThread>();
        }
    
        public int TagId { get; set; }
        public string TagText { get; set; }
    
        public virtual ICollection<TagThread> TagThreads { get; set; }
    }
}
