//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Forum_cSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagThread
    {
        public int Id { get; set; }
        public int TagId { get; set; }
        public int ThreadId { get; set; }
    
        public virtual Thread Thread { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
