//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Forum_cSharp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Thread
    {
        public Thread()
        {
            this.TagThreads = new HashSet<TagThread>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int ThreadId { get; set; }
        [Required,StringLength(50)]
        public string Title { get; set; }
        [Required]
        public string Content { get; set; }
        public string UserName { get; set; }
        public System.DateTime Date { get; set; }
        public int Views { get; set; }
        public int Upvotes { get; set; }
    
        public virtual ICollection<TagThread> TagThreads { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
